modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="tardis_mod"
version="1.0.0"
displayName="TARDIS MOD"
displayURL="https://mcreator.net"
credits="what"
authors="what"
description="what"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tardis_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration