modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="tardis_mod"
version="1.0.0"
displayName="TARDIS MOD"
displayURL="https://mcreator.net"
credits="what"
authors="what"
description="what"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tardis_mod]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tardis_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration